steps:
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: 'gcloud'
  args: ['functions', 'deploy', 'pull-request-summary', '--source', 'https://source.developers.google.com/projects/test-project-miguel/repos/github_miguelortize_github-weekly-report/moveable-aliases/main/paths/python_functions/github_weekly_report', '--trigger-http', '--runtime', 'python312', '--allow-unauthenticated']
