name: Weekly Pull Request Summary

on:
  workflow_dispatch:
  schedule:
    # Runs at 00:00 UTC every Monday
    - cron: '0 0 * * 1'

jobs:
  call-cloud-function:
    runs-on: ubuntu-latest
    env:
      GITHUB_USER: kubernetes
      GITHUB_REPO: kubernetes
    steps:
    - name: Call Google Cloud Function
      run: |
        curl -X GET "https://us-central1-test-project-miguel.cloudfunctions.net/pull-request-summary?user=${{ env.GITHUB_USER }}&repo=${{ env.GITHUB_REPO }}"
